### ISSUE TITLE
Doesn't compile with Zig 0.10.1

### ISSUE THREAD

**Issue by YakBarber** [canadaduane/cleartouch#2]
I'm on Zig version `0.10.1`. I was attempting to build this via the Archlinux User Repository definition https://aur.archlinux.org/packages/cleartouch-git, but on build error decided to try and investigate myself.

I started by fixing the deprecated symbol issues. At the top of `build.zig` I changed `addIncludeDir` to `addIncludePath`, and `addLibPath` to `addLibraryPath`. Then I got this error:

```
➜ cleartouch zig build -Drelease-small=true                                                                                                                                              git:(makepkg|✚6…8
/home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/clap/clap/comptime.zig:156:6: error: empty test name must be omitted
test "" {
     ^~
/home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/clap/clap.zig:108:12: error: value with comptime-only type '@TypeOf(null)' depends on runtime control flow
    } else if (short_name == null) {
           ^~
/home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/clap/clap.zig:106:16: note: runtime control flow here
    } else if (found_comma) {
               ^~~~~~~~~~~
referenced by:
    main: /home/barry/.cache/yay/cleartouch-git/src/cleartouch/src/main.zig:48:13
    callMain: /usr/lib/zig/std/start.zig:614:32
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

error: cleartouch...
error: The following command exited with error code 1:
/usr/bin/zig build-exe /home/barry/.cache/yay/cleartouch-git/src/cleartouch/src/main.zig -lc -ludev -cflags -std=gnu99 -DPLATFORM_DESKTOP -DGL_SILENCE_DEPRECATION -fno-sanitize=undefined -- /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/raylib/src/rcore.c -cflags -std=gnu99 -DPLATFORM_DESKTOP -DGL_SILENCE_DEPRECATION -fno-sanitize=undefined -- /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/raylib/src/rmodels.c -cflags -std=gnu99 -DPLATFORM_DESKTOP -DGL_SILENCE_DEPRECATION -fno-sanitize=undefined -- /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/raylib/src/raudio.c -cflags -std=gnu99 -DPLATFORM_DESKTOP -DGL_SILENCE_DEPRECATION -fno-sanitize=undefined -- /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/raylib/src/rshapes.c -cflags -std=gnu99 -DPLATFORM_DESKTOP -DGL_SILENCE_DEPRECATION -fno-sanitize=undefined -- /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/raylib/src/rtext.c -cflags -std=gnu99 -DPLATFORM_DESKTOP -DGL_SILENCE_DEPRECATION -fno-sanitize=undefined -- /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/raylib/src/rtextures.c -cflags -std=gnu99 -DPLATFORM_DESKTOP -DGL_SILENCE_DEPRECATION -fno-sanitize=undefined -- /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/raylib/src/utils.c -cflags -std=gnu99 -DPLATFORM_DESKTOP -DGL_SILENCE_DEPRECATION -fno-sanitize=undefined -- /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/raylib/src/rglfw.c -lGL -lX11 -OReleaseSmall --cache-dir /home/barry/.cache/yay/cleartouch-git/src/cleartouch/zig-cache --global-cache-dir /home/barry/.cache/zig --name cleartouch --pkg-begin pike /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/pike/pike.zig --pkg-end --pkg-begin clap /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/clap/clap.zig --pkg-end -I /home/barry/.cache/yay/cleartouch-git/src/cleartouch/raylib/include -I /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/raylib/src -I /home/barry/.cache/yay/cleartouch-git/src/cleartouch/lib/raylib/src/external/glfw/include -L raylib/lib --enable-cache
error: the following build command failed with exit code 1:
/home/barry/.cache/yay/cleartouch-git/src/cleartouch/zig-cache/o/4d1b201d965b98b0d5654990c81a462a/build /usr/bin/zig /home/barry/.cache/yay/cleartouch-git/src/cleartouch /home/barry/.cache/yay/cleartouch-git/src/cleartouch/zig-cache /home/barry/.cache/zig -Drelease-small=true
```

I'm not a Zig person, so I've stopped here.

**Comment by canadaduane** [comment]
I need to take a look at how zig has changed--I'm not yet a "zig person" either :D

Thanks for bringing this up though.
